django/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^questionnaire/', include('questionnaire.urls', namespace='questionnaire')),
    url(r'^response/', include('response.urls', namespace='response')),
]

django/questionnaire/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^entry/patient_id/(?P<patient_id>[\d\w]+)$', entryView, name='entry'),
    url(r'^(?P<qid>[0-9]+)/patient_id/(?P<patient_id>[\d\w]+)/$', questionView, name='view'),
    url(r'^(?P<qid>[0-9]+)/patient_id/(?P<patient_id>[\d\w]+)/submit/$', submitAnswers, name='submit'),
    url(r'^about/$', TemplateView.as_view(template_name='questionnaire/about.html'), name='about'),

    url(r'login/$', auth_views.login, {'template_name': 'questionnaire/login.html'}, name='login'),
    url(r'logout/$', auth_views.logout, {'template_name': 'questionnaire/logout.html'}, name='logout'),
]

django/questionnaire/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, 
# modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field 
# names.
from __future__ import unicode_literals

from django.db import models


class Questionnaire(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.TextField()
    description = models.TextField()

    def __str__(self):
        return str(self.id) + ". " + self.title

    class Meta:
        managed = False
        db_table = 'questionnaire'


class Question(models.Model):
    QUESTION_TYPES = (('SCALE', 'Scale'), ('SINGLE', 'Single Choice'))
    id = models.AutoField(primary_key=True)
    questionnaire = models.ForeignKey(Questionnaire)
    question_order = models.PositiveSmallIntegerField()  # max: 32767
    question_text = models.TextField()
    question_type = models.CharField(max_length=25, choices=QUESTION_TYPES,
                                     default='SINGLE')

    def __str__(self):
        # return str(self.id) + ". " + self.question_text
        return '[QN{}] Q{}. {}'.format(self.questionnaire.id,
                                       self.question_order,
                                       self.question_text)

    class Meta:
        managed = False
        db_table = 'question'


class Option(models.Model):
    id = models.AutoField(primary_key=True)
    question = models.ForeignKey(Question)
    option_order = models.SmallIntegerField()  # max: +/-32767
    option_text = models.TextField()
    score = models.IntegerField()

    def __str__(self):
        # return str(self.question.id) + "." + str(
        #     self.option_order) + " " + self.option_text + "  " + str(
        # self.score)
        return '[QN{}] Q{}. {} OP{}. {} (score={})'.format(
            self.question.questionnaire.id,
            self.question.question_order,
            self.question.question_text[:30] + '... ',
            self.option_order,
            self.option_text,
            self.score)

    class Meta:
        managed = False
        db_table = 'option'


class Answer(models.Model):
    id = models.AutoField(primary_key=True)
    question = models.ForeignKey(Question)
    patient_id = models.PositiveIntegerField()  # max: 2147483647
    submit_date = models.DateField()
    response = models.TextField()
    note = models.TextField(null=True)

    def __str__(self):
        return str(self.id)

    class Meta:
        managed = False
        db_table = 'answer'

django/questionnaire/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from questionnaire.models import *
from django.db.models import Q
from django.utils import timezone
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy


def index(request):
    return HttpResponse("You're looking at question.")


@login_required(login_url=reverse_lazy('questionnaire:login'))
def entryView(request, patient_id):
    today = timezone.now()
    context = {'weekly': False, 'monthly': False, 'patient_id': patient_id}
    # Weekly questionnaire is answered every Friday. 
    if today.weekday() == 5:
        context['weekly'] = True
    # Monthly questionnaire is answered at 1st-3rd every month.
    if today.day <= 3:
        context['monthly'] = True
    return render(request, 'questionnaire/entry.html', context)


@login_required(login_url=reverse_lazy('questionnaire:login'))
def questionView(request, qid, patient_id):
    context = {'questionnaire': None,
               'patient_id': patient_id,
               'questions': []}

    context['questionnaire'] = Questionnaire.objects.get(id=qid)

    questions = Question.objects.filter(questionnaire__id=qid).order_by(
        'question_order')
    for question in questions:
        qobj = {'id': question.id,
                'order': question.question_order,
                'question_text': question.question_text,
                'type': question.question_type,
                'options': Option.objects.filter(
                    Q(question__id=question.id) & Q(option_order__gt=0))
                    .order_by('option_order'),
                }

        if qobj['type'] == 'SCALE':
            # Option order == -1 is the left label.
            # Option order == 0 is the right label. 
            qobj['labels'] = Option.objects.filter(
                Q(question__id=question.id) & Q(option_order__lte=0)
            ).values_list('option_text', flat=True).order_by('option_order')

        context['questions'].append(qobj)
    return render(request, 'questionnaire/question.html', context)


@login_required(login_url=reverse_lazy('questionnaire:login'))
def submitAnswers(request, qid, patient_id):
    """ 
        If submit is successful, return 
            {"status": true, "patient_id": xxx, "submit_date": today's date}
        If submit fails, return 
            {"status": true, "patient_id": xxx, "submit_date": today's date, 
             "error_msg": msg}
    """
    template = 'questionnaire/submit.html'
    submit_date = timezone.now()
    context = {
        'patient_id': patient_id,
        'submit_date': submit_date,
        'status': False
    }
    questions = Question.objects.filter(questionnaire=qid).order_by('id')

    if request.method == "POST":
        try:
            responses = {q: None for q in questions}

            # Validate every question is answered
            for question in questions:
                answer = request.POST.get(str(question.id), None)
                if answer == '' or answer is None:
                    if not (qid == '1' and question.id > 8):
                        raise Exception(question.question_order)
                else:
                    responses[question] = answer

            # check questionnaire 1: 9, 10, 11 questions should only has one 
            # answer. 
            if qid == '1':
                extra_q = []
                for q, a in responses.iteritems():
                    if q.question_order > 8:
                        extra_q.append(a is not None)
                if not any(extra_q) or extra_q.count(True) > 1:
                    raise Exception(9)

            # Save every question. 
            for question, answer in responses.iteritems():
                if answer is None:
                    continue
                answer = Answer(question=question,
                                submit_date=submit_date,
                                patient_id=patient_id,
                                response=answer,
                                note="")
                answer.save()
            context['status'] = True
        except IntegrityError as e:
            context['error_msg'] = e.message
        except Exception as err:
            context['error_msg'] = 'Question #{} is incomplete'.format(
                err.args[0])

    else:
        context['error_msg'] = 'Form is invalid.'

    return render(request, template, context)

django/questionnaire/templates/questionnaire/about.html
{% extends "questionnaire/base.html" %}
{% load static %}

{% block body %}
<div class="text-center">
    <img src="{% static 'questionnaire/logo.jpg' %}" 
         style="max-width: 200px;"/>
    <p>Your participation in this survey is voluntary. </p>
    <p>This research project is conducted by <br/>
        Karin Grävare Silbernagel PT, PhD, ATC <br/>
        at Department of Physical Therapy, University of Delaware. </p>
    <p>You can contact the research team via email 
        <a href="mailto:tendonreasearch@udel.edu">tendonreasearch@udel.edu</a>.</p>
</div>
{% endblock %}

django/questionnaire/templates/questionnaire/base.html
{% load static %}

<html>
<head>
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
            integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" 
            crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,300i,400"
          rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
            integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
            crossorigin="anonymous"></script>
    
    {% block script %} {% endblock %}
   
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>

{% block nav %} {% endblock %}

<body>
    {% block body %} {% endblock %}
</body>
</html>

django/questionnaire/templates/questionnaire/contact.html
<h5>Contact us: <a href="mailto:tendonreasearch@udel.edu" target="_top">tendonreasearch@udel.edu</a></h5>
<p><a href="{% url 'questionnaire:about' %}"> About the survery </a></p>
<br/>

django/questionnaire/templates/questionnaire/entry.html
{% extends "questionnaire/base.html" %}
{% load static %}

{% block body %}
<div class="text-center" style="padding: 20px;">
    {% if weekly %} 
        <a role="button"
           class="btn btn-primary btn-block"
           href="{% url 'questionnaire:view' 2 patient_id%}">
                Go to weekly questionnaire.</a>
    {% endif %}

    {% if monthly %}
    <a role="button"
       class="btn btn-primary btn-block"
       href="{% url 'questionnaire:view' 1 patient_id%}">
        Go to monthly questionnaire.</a>
    {% endif %}

    {% if not weekly and not monthly %}
        There is no questionnaire available at this time. 
    {% endif %}
    
    <br/>
    {% include 'questionnaire/contact.html' %}
</div>
{% endblock %}

django/questionnaire/templates/questionnaire/login.html
{% extends "questionnaire/base.html" %}
{% load static %}

{% block body %}
<div class="text-center">    

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<img src="{% static 'questionnaire/logo.jpg' %}"
     style="max-width: 200px;"/>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-default">Login</button>
    <button type="button" class="btn btn-default">
        <a href="{% url 'questionnaire:logout' %}">logout</a></button>
</form>
</div>
<script>
    // Fill username field. 
    // Get query string
    // http://stackoverflow.com/questions/901115/how-can-i-get-query-string-values-in-javascript
    var qd = {};
    if (location.search) location.search.substr(1).split("&").forEach(function(item) {var s = item.split("="), k = s[0], v = s[1] && decodeURIComponent(s[1]); (qd[k] = qd[k] || []).push(v)})
    $('#id_username').val(qd['username']);
</script>
{% endblock %}

django/questionnaire/templates/questionnaire/logout.html
{% extends "questionnaire/base.html" %}
{% load static %}

{% block body %}
<div class="text-center">
<h3>Logged out!</h3>
<br/>

<button type="button" class="btn btn-default">
    <a href="{% url 'questionnaire:login' %}">Re-login</a>
</button>
</div>
{% endblock %}

django/questionnaire/templates/questionnaire/question.html
{% extends "questionnaire/base.html" %}
{% load static %}


{% block script %}
    <link href="{% static 'questionnaire/style.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'questionnaire/function.js' %}?v=2"></script>
{% endblock %}

{% block nav %}
<nav class="navbar-fixed-top survey-progress-bar">
    <div class="survey-progress-bar-div">
        <div class="btn-group btn-group-justified">
            {% for question in questions %}
                {% if question.order < 10 %}
                    <a href="#question-{{question.order}}" 
                       id="progress-{{question.order}}" 
                       class="btn btn-default-color btn-nav" 
                       role="button">{{question.order}}</a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</nav>
{% endblock %}

{% block body %} 
<p>Patient ID: {{patient_id}} &nbsp;&nbsp;&nbsp;
    <a href="{% url 'questionnaire:logout' %}">Log out</a>
</p>

<h2 class="text-center">{{questionnaire.title}}</h2>
<blockquote><small>{{questionnaire.description}}</small></blockquote>
<hr>

<form action="{% url 'questionnaire:submit' questionnaire.id patient_id %}" 
      method="post">
    {% csrf_token %}
    <div class="container-fluid">
        {% for question in questions %}
        <div id="{{questionnaire.id}}-{{question.order}}">
            <span id="question-{{question.order}}">
            	<label class="question-label">
                	<span class="question_id">{{question.order}}. </span>{{question.question_text}}</label></span>
            {% if question.type == 'SCALE' %}
            <div class="one-question-domain">
                <label class="one-question-domain-left">{{question.labels.0}}</label>
                <label class="one-question-domain-right">{{question.labels.1}}</label>
                <div class="btn-group btn-group-justified">
                    {% for option in question.options%}
                    <div class="btn-group" role="group">
                        <button type="button"
                                name="{{question.id}}"
                                order="{{question.order}}"
                                value="{{option.id}}"
                                class="btn btn-default">
                            {{option.option_text}}
                        </button>
                    </div>
                    {% endfor %}
                </div> 
            </div>
            <input type="hidden" value="" name="{{question.id}}">
            {% else %}
            <div>
                {% for option in question.options%}
                <div class="radio">
                    <label><input type="radio"
                                  name="{{question.id}}"
								  order="{{question.order}}"
                                  value="{{option.id}}">
                        {{option.option_text}}</label>
                </div>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    <hr>
    <button type="submit" class="btn btn-success btn-block">Submit</button>
</form>
{% endblock %}

django/questionnaire/templates/questionnaire/submit.html
{% extends "questionnaire/base.html" %}
{% load static %}

{% block body %}
<div class="text-center">
{% if status %}
    <h1><span class="glyphicon glyphicon-ok-circle panel-heading text-success"></span></h1>
    <h5>Thank you!</h5>
    <h5>Your answers have been successfully saved!</h5>
{% else %}
    <h1><span class="glyphicon glyphicon-exclamation-sign panel-heading text-danger"></span></h1>
    <h5>Something went wrong. Please try again later.</h5>
    <small> {{error_msg}} </small>
    {% include 'questionnaire/contact.html' %}
{% endif %}

<br>
<div>        
    <p><span class="glyphicon glyphicon-user"></span>Patient id: {{patient_id}}</p>
    <p><span class="glyphicon glyphicon-calendar"></span>Submit date: {{submit_date}}</p>
</div>
</div>
{% endblock %}