django/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^questionnaire/', include('questionnaire.urls', namespace='questionnaire')),
    url(r'^response/', include('response.urls', namespace='response')),
]

django/questionnaire/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^entry/patient_id/(?P<patient_id>[\d\w]+)$', entryView, name='entry'),
    url(r'^(?P<qid>[0-9]+)/patient_id/(?P<patient_id>[\d\w]+)/$', questionView, name='view'),
    url(r'^(?P<qid>[0-9]+)/patient_id/(?P<patient_id>[\d\w]+)/submit/$', submitAnswers, name='submit'),
    url(r'^about/$', TemplateView.as_view(template_name='questionnaire/about.html'), name='about'),

    url(r'login/$', auth_views.login, {'template_name': 'questionnaire/login.html'}, name='login'),
    url(r'logout/$', auth_views.logout, {'template_name': 'questionnaire/logout.html'}, name='logout'),
]

django/response/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from views import *

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='response/index.html'), name='index'),
    url(r'view/$', responseTable, name='view'),
    url(r'track/$', trackView, name='track')
]

django/response/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .search_forms import ResponseForm
from django.db import connection
from questionnaire.models import *
import json


def db_execute(query):
    with connection.cursor() as cursor:
        cursor.execute(query)
        return cursor.fetchall()


def generate_query(form):
    where_conditions = []
    if form['questionnaire_id']:
        where_conditions.append(
            "question.questionnaire_id = {}".format(form['questionnaire_id']))
    if form['patient_id']:
        where_conditions.append(
            "patient_id = {}".format(form['patient_id'])
        )
    # DateTime

    where_stm = ""
    if len(where_conditions):
        where_stm = "WHERE " + " AND ".join(where_conditions)

    query = """
        SELECT patient_id, submit_date, 
            GROUP_CONCAT(question.question_order || '-' || option.option_order) as answers, 
            SUM(option.score)
        FROM answer 
          JOIN question ON answer.question_id = question.id
          JOIN option ON answer.response = option.id
        {}
        GROUP BY question.questionnaire_id, patient_id, submit_date
    """.format(where_stm)
    return query


def index(request):
    context = {'form': None, 'table': {}}
    if request.method == "POST":
        form = ResponseForm(request.POST)
        context['form'] = form
        if form.is_valid():
            form_data = form.cleaned_data
            question_count = Question.objects.filter(
                questionnaire=form_data['questionnaire_id']).count()
            question_title = map(str, range(1, question_count + 1))
            title = ['Patient id', 'Submit date'] + question_title + ['Total Score']

            data = []
            query = generate_query(form_data)
            for record in db_execute(query):
                responses = {str(i): '' for i in range(1, question_count + 1)}
                for col in record[2].split(','):
                    idx, response = col.split('-')
                    responses[idx] = response

                # sorted patient response by key
                row = [responses[k] for k in sorted(responses, key=int)]
                data.append(map(str, record[:2]) + row + [record[3]])

            context['table'] = {
                'columns': title,
                'data': json.dumps(data)
            }
    else:
        context['form'] = ResponseForm()

    return render(request, 'response/index.html', context)

django/response/views/index.py
from django.shortcuts import render
from .utils import *
from response.search_forms import ResponseForm
from questionnaire.models import *
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy
import json


@user_passes_test(lambda u: u.is_superuser,
                  login_url=reverse_lazy('questionnaire:login'))
def index(request):
    context = {'form': None, 'table': {}}
    if request.method == "POST":
        form = ResponseForm(request.POST)
        context['form'] = form
        if form.is_valid():
            form_data = form.cleaned_data
            question_count = Question.objects.filter(
                questionnaire=form_data['questionnaire_id']).count()
            question_title = map(str, range(1, question_count + 1))
            title = ['Patient id', 'Submit date'] + question_title + [
                'Total Score']

            data = []
            query = generate_query(form_data)
            for record in db_execute(query):
                responses = {str(i): '' for i in range(1, question_count + 1)}
                for col in record[2].split(','):
                    idx, response = col.split('-')
                    responses[idx] = response

                # sorted patient response by key
                row = [responses[k] for k in sorted(responses, key=int)]
                data.append(map(str, record[:2]) + row + [record[3]])

            context['table'] = {
                'columns': title,
                'data': json.dumps(data)
            }
    else:
        context['form'] = ResponseForm()

    return render(request, 'response/index.html', context)

django/response/views/responseTable.py
from django.shortcuts import render
from .utils import *
from response.search_forms import ResponseForm
from questionnaire.models import *
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy
import json


@user_passes_test(lambda u: u.is_superuser,
                  login_url=reverse_lazy('questionnaire:login'))
def responseTable(request):
    context = {'form': None, 'table': {}}
    if request.method == "POST":
        form = ResponseForm(request.POST)
        context['form'] = form
        if form.is_valid():
            form_data = form.cleaned_data
            question_count = Question.objects.filter(
                questionnaire=form_data['questionnaire_id']).count()
            question_title = map(str, range(1, question_count + 1))
            title = ['Patient id', 'Submit date'] + question_title + [
                'Total Score']

            data = []
            query = generate_query(form_data)
            for record in db_execute(query):
                responses = {str(i): '' for i in range(1, question_count + 1)}
                for col in record[2].split(','):
                    idx, response = col.split('-')
                    responses[idx] = response

                # sorted patient response by key
                row = [responses[k] for k in sorted(responses, key=int)]
                data.append(map(str, record[:2]) + row + [record[3]])

            context['table'] = {
                'columns': title,
                'data': json.dumps(data)
            }
    else:
        context['form'] = ResponseForm()

    return render(request, 'response/response.html', context)

django/response/views/track.py
from django.shortcuts import render
from .utils import *
from response.search_forms import TrackForm
from questionnaire.models import *
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy
import json


def track_data_format(data):
    """ Reformat database result to Google Chart format. 
    Args: 
        data (list): [[patient_id, submit_date, responses_string, total_score]]
    Returns: 
        Google Chart Data Table Format in json format
        https://developers.google.com/chart/interactive/docs/reference#DataTable
        First column: Date
        Second column: total_score
    """

    columns = [{"label": 'Date', "type": "string"},
               {"label": 'Severity Score', "type": "number"}]
    rows = []
    for line in data:
        rows.append({"c": [{"v": str(line[1])},
                           {"v": int(line[3])}
                           ]})

    return json.dumps({"cols": columns, "rows": rows})


@user_passes_test(lambda u: u.is_superuser,
                  login_url=reverse_lazy('questionnaire:login'))
def trackView(request):
    context = {'form': None, 'data': {}, 'error': None}
    if request.method == "POST":
        form = TrackForm(request.POST)
        context['form'] = form
        if form.is_valid():
            form_data = form.cleaned_data
            if form_data['patient_id'] is None:
                context['form'] = TrackForm()
                context['error'] = "Patient id is required."
            else:
                # Get data from every questionnaire
                for qid in [1, 2]:
                    form_data['questionnaire_id'] = qid
                    query = generate_query(form_data)
                    context['data'][qid] = {
                        'title': str(Questionnaire.objects.get(id=qid).title),
                        'data': track_data_format(db_execute(query))
                    }
    else:
        context['form'] = TrackForm()

    return render(request, 'response/track.html', context)

django/response/views/utils.py
from django.db import connection

def db_execute(query):
    with connection.cursor() as cursor:
        cursor.execute(query)
        return cursor.fetchall()


def generate_query(form):
    where_conditions = []
    if form['questionnaire_id']:
        where_conditions.append(
            "question.questionnaire_id = {}".format(form['questionnaire_id']))
    if form['patient_id']:
        where_conditions.append(
            "patient_id = {}".format(form['patient_id'])
        )
    # DateTime

    where_stm = ""
    if len(where_conditions):
        where_stm = "WHERE " + " AND ".join(where_conditions)

    query = """
        SELECT patient_id, submit_date, 
            GROUP_CONCAT(question.question_order || '-' || option.option_order) as answers, 
            SUM(option.score)
        FROM answer 
          JOIN question ON answer.question_id = question.id
          JOIN option ON answer.response = option.id
        {}
        GROUP BY question.questionnaire_id, patient_id, submit_date
        ORDER BY submit_date
    """.format(where_stm)
    return query

django/response/templates/response/index.html
{% extends "questionnaire/base.html" %}

{% block body %}
<div style="padding:20px;">
    <h3> Admin views <small> (superuser required)</small></h3>
    <p><a href="/admin"> Admin page </a></p>
    <p><a href="{% url 'response:view' %}"> Patient response view </a></p>
    <p><a href="{% url 'response:track' %}"> Severity score chart </a></p>
    
    <h3> Patient views</h3>
    <p><a href="{% url 'questionnaire:entry' 0 %}"> Survey entry point </a></p>
    <p><a href="{% url 'questionnaire:view' 1 0 %}"> Questionnaire 1 </a></p>
    <p><a href="{% url 'questionnaire:view' 2 0 %}"> Questionnaire 2 </a></p>
    
</div>
{% endblock %}

django/response/templates/response/response.html
{% extends "questionnaire/base.html" %}
{% load static %}

{% block script %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<link href="{% static 'response/jquery-ui-datepicker.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'response/jquery-ui.structure.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'response/jquery-ui.theme.min.css' %}" rel="stylesheet" type="text/css">
<script src="{% static 'response/jquery-ui-datepicker.min.js' %}"></script>
<script>
    $(function(){
        var dataset = {{ table|safe}};
        if (dataset.columns) {
            $('#table').DataTable( {
                data: eval(dataset.data),
                columns: dataset.columns.map(function(ele){
                    return {title: ele};
                }),
                dom: 'Bi',
                buttons: ['copy', 'csv', 'excel']
            });
        }
        
        // http://api.jqueryui.com/datepicker/#option-dateFormat
        $("#id_date_from").datepicker(
        );
        $("#id_date_to").datepicker();
    });
</script>
<!--https://datatables.net/download/-->
<!-- With extensions: buttons, html5 export, jszip -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.13/b-1.2.4/b-html5-1.2.4/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.13/b-1.2.4/b-html5-1.2.4/datatables.min.js"></script>
<style>
    body {
        padding: 20px;
        padding-top: 80px;
    }
    table {
        font-size: 12px;
    }
</style>
{% endblock %}


{% block nav %}
<nav class="navbar navbar-form navbar-fixed-top">
    <div class="container-fluid">
        <form id="query" action="" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
</nav>
{% endblock %}

{% block body %}
<table id="table" class="table table-border"></table>
{% endblock %}

django/response/templates/response/track.html
{% extends "questionnaire/base.html" %}
{% load static %}

{% block script %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
$(document).ready(function () {
    var data = {{data|safe}};

    if (!$.isEmptyObject(data)) {
        google.charts.load('current', {'packages': ['corechart', 'table']});
        google.charts.setOnLoadCallback(drawChart);
        function drawChart() {
            var questionnaire = data[1];
            var linedata = new google.visualization.DataTable(questionnaire.data);
            var linechart = new google.visualization.LineChart($('#linechart')[0]);
            linechart.draw(linedata, {
                title: questionnaire.title,
                width: 1000,
                height: 400,
                hAxis: { slantedText: true},
                vAxis: {
                    title: 'Severity Score',
                    format: '0',
                    minValue: 0
                },
                legend: 'none',
                series: {
                    0: {
                        pointShape: 'circle',
                        pointSize: 10,
                        color: 'blue'
                    }
                }
            });
            var linetable = new google.visualization.Table($('#linetable')[0]);
            linetable.draw(linedata);

            var questionnaire2 = data[2];
            var linedata2 = new google.visualization.DataTable(questionnaire2.data);
            var linechart2 = new google.visualization.LineChart($('#linechart2')[0]);
            linechart2.draw(linedata2, {
                title: questionnaire2.title,
                width: 1000,
                height: 400,
                hAxis: { slantedText: true},
                vAxis: {
                    title: 'Severity Score',
                    format: '0',
                    minValue: 0
                },
                legend: 'none',
                series: {
                    0: {
                        pointShape: 'triangle',
                        pointSize: 10,
                        color: 'red'
                    }
                }
            });
            var linetable2 = new google.visualization.Table($('#linetable2')[0]);
            linetable2.draw(linedata2);
        }
    }
});
</script>
<style>
    body {
        padding: 20px;
        padding-top: 80px;
    }
    nav {
        background-color: #fff;
    }
    table {
        font-size: 12px;
    }
</style>
{% endblock %}


{% block nav %}
<nav class="navbar navbar-form navbar-fixed-top">
    <div class="container-fluid">
        <form id="query" action="" method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
</nav>
{% endblock %}

{% block body %}
{% if error %}{{error}}{% endif %}
{% if data %}
<table class="table table-border">
    <tr>
        <td class="col-md-10"><div id="linechart"></div></td>
        <td class="col-md-2">
            <button class="btn btn-default btn-xs"
                     data-toggle="collapse" data-target="#linetable">
                    Show Data</button>
            <div id="linetable" class="collapse"></div>
        </td>
    </tr>
    <tr>
        <td class="col-md-10"><div id="linechart2"></div></td>
        <td class="col-md-2">
            <button class="btn btn-default btn-xs"
                     data-toggle="collapse" data-target="#linetable2">
                    Show Data</button>
            <div id="linetable2" class="collapse"></div>
        </td>
    </tr>
</table>
{% endif %}
{% endblock %}